version: '3.8'

services:
  db:
    image: mysql:8.0.32
    container_name: nsdocs_db
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nsdocs_consumption
      - TZ=America/Sao_Paulo
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/home/scripts
    ports:
      - "3306:3306"
    command:
      - '--skip-log-bin'
      - '--default-authentication-plugin=mysql_native_password'
      - '--sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    network_mode: bridge
volumes:
  db_data:
